### ISSUE TITLE
Reverse compliment wrong

### ISSUE THREAD

**Issue by anniewly** [LucaCappelletti94/ucsc_genomes_downloader#4]
Hello,

Thank you for writing this software!

I am currently working with both plus strand and minus strand. I realized that this software is paring A with G and C with T as shown in the below example. Both command are extracting from the same location on the same chromosome, except the top command has strand parameter set to '+' and the bottom has set to '-'. 

```
>>> mm10.extract_sequence(chrom='chr1',chromStart=9877089,chromEnd=9877099,strand='+')
'TCTGTTTCTG'
>>> mm10.extract_sequence(chrom='chr1',chromStart=9877089,chromEnd=9877099,strand='-')
'CTCACCCTCA'
```

**Comment by LucaCappelletti94** [comment]
Thank you for bringing this to my attention, I had checked against the genome browser  that it worked fine but evidently it doesn't. Could you provide a small list of sequences and their coordinates? I'd like to update the test suite and fix this.

**Comment by LucaCappelletti94** [comment]
Re-reading your issue I understood that it was a simple matter of typos, sorry yesterday it was quite late and I thought I was querying the wrong region. I am fixing this.

**Comment by LucaCappelletti94** [comment]
Just released the updated version! Should be quite fixed, but do feel free to reopen if the error somehow remains.
